### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by Phibedy** [Phibedy/lmsPythonModules#2]
- [ ] Every module should get its own context.
- [ ] Connection to lms (Write Module)
- [ ] improve data handling
  - [ ] Serialization?
